apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingress.yaml
- secret.yaml
- service.yaml
- postgres-secret.yaml
- postgres-service.yaml
- postgres-deployment.yaml
- configmap.yaml
- pingpong-deployment.yaml
- logoutput-deployment.yaml
namespace: pingpong-logoutput
images:
- name: logoutput
  newName: gcr.io/gke-dwe/logoutput
  newTag: main-efca70d66ab6699d9878af63a17bb831eeb00493
- name: pingpong
  newName: gcr.io/gke-dwe/pingpong
  newTag: main-efca70d66ab6699d9878af63a17bb831eeb00493
- name: reader
