apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingress.yaml
- secret.yaml
- service.yaml
- postgres-secret.yaml
- postgres-service.yaml
- postgres-deployment.yaml
- configmap.yaml
- pingpong-deployment.yaml
- logoutput-deployment.yaml
images:
- name: logoutput
  newTag: ""
- name: reader
  newTag: ""