apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pingpong-logoutput
  labels:
    app: postgres
stringData:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: strongpass0000